### ISSUE TITLE
Replace structure based xpath with style-based xpath

### ISSUE THREAD

**Issue by FullBinaryAlchemist** [hopto-dot/JPDB-Discord-Bot#1]
https://github.com/hopto-dot/JPDB-Discord-Bot/blob/6754da43483aaea426f21c084964e108bf687fe7/JPDB%20Bot/Commands.cs#L157

Rather than using a hard-coded xpath like that, you can try using xpath based on style selector. 
Try installing the extension "Chro-path" and see the xpath in that

**Comment by hopto-dot** [comment]
Thank you, I'll see what I can do. As you may have noticed I am still very bad at coding.
